# WARNING - Generated by {fusen} from dev/flat_search_folder_size.Rmd: do not edit by hand


test_that("search_folder_size returns a data.frame", {
  temp_dir <- tempdir()
file1 <- file.path(temp_dir, "file1.csv")
file2 <- file.path(temp_dir, "file2.csv")
file3 <- file.path(temp_dir, "file3.csv")
write.csv(iris, file1, row.names = FALSE)
write.csv(mtcars, file2, row.names = FALSE)
write.csv(head(mtcars), file3, row.names = FALSE)  # Plus petit fichier

  result <- search_folder_size(temp_dir, 1000)
  expect_true(is.data.frame(result))
})

test_that("search_folder_size handles no files above threshold", {
   temp_dir <- tempdir()
file1 <- file.path(temp_dir, "file1.csv")
file2 <- file.path(temp_dir, "file2.csv")
file3 <- file.path(temp_dir, "file3.csv")
write.csv(iris, file1, row.names = FALSE)
write.csv(mtcars, file2, row.names = FALSE)
write.csv(head(mtcars), file3, row.names = FALSE)  # Plus petit fichier

  result <- search_folder_size(temp_dir, 100000)
  expect_equal(nrow(result), 0)
})




