# WARNING - Generated by {fusen} from dev/flat_get_one_file_size.Rmd: do not edit by hand



# Début des tests unitaires
test_that("get_one_file_size returns a data.frame", {
  temp_filename <- tempfile(fileext = ".csv")
write.csv(iris, temp_filename, row.names = FALSE)
  result <- get_one_file_size(temp_filename)
  expect_true(is.data.frame(result))
})

test_that("get_one_file_size returns correct file name", {
  temp_filename <- tempfile(fileext = ".csv")
write.csv(iris, temp_filename, row.names = FALSE)
  result <- get_one_file_size(temp_filename)
  expect_equal(result$file_name, temp_filename)
})


