# WARNING - Generated by {fusen} from dev/flat_get_all_file_size.Rmd: do not edit by hand

library(purrr)
library(dplyr)
temp_dir <- tempdir()
file1 <- file.path(temp_dir, "file1.csv")
file2 <- file.path(temp_dir, "file2.csv")
write.csv(iris, file1, row.names = FALSE)
write.csv(mtcars, file2, row.names = FALSE)

# Début des tests unitaires
test_that("get_all_file_size returns a data.frame", {
  result <- get_all_file_size(temp_dir)
  expect_true(is.data.frame(result))
})


test_that("get_all_file_size handles empty directory", {
  empty_dir <- tempfile()
  dir.create(empty_dir)
  result <- get_all_file_size(empty_dir)
  expect_true(is.data.frame(result))
  expect_equal(nrow(result), 0)
  unlink(empty_dir)
})
