# WARNING - Generated by {fusen} from dev/flat_get_all_file_size.Rmd: do not edit by hand

#' get_all_file_size Title
#' Elle prend un chemin de dossier en paramètre, et map la fonction get_one_file_size pour n’obtenir qu’un seul tableau.
#'
#' @param directory un chemin de dossier
#'
#' @return 1 tableau
#' @export
#' @importFrom purrr map
#' @importfrom dplyr bind_rows
#' @examples
#' library(purrr)
#' library(dplyr)
#' get_all_file_size(directory = ".")
get_all_file_size <- function(directory) {
  # Obtenir la liste des fichiers dans le répertoire
  files <- list.files(directory, full.names = TRUE)
  
  # Appliquer la fonction get_one_file_size à chaque fichier
  file_sizes <- map(files, get_one_file_size)
  
  # Combiner les résultats en un seul data.frame
  result <- dplyr::bind_rows(file_sizes)
  
  return(result)
}
