# WARNING - Generated by {fusen} from dev/flat_get_one_file_size.Rmd: do not edit by hand

#' get_one_file_size 
#'
#'Récupère un fichier pour en sortir un dataframe et sa taille.
#' @param file un nom de fichier 
#'
#' @return un dataframe avec son nom et sa taille
#' @export
#'
#' @examples
#' temp_filename <- tempfile(fileext = ".csv")
#' write.csv(iris, temp_filename, row.names = FALSE)
#' get_one_file_size(temp_filename)
#'
#' get_one_file_size(file = "analyse_facto.Rmd")
#'
get_one_file_size <- function(file) {
  file_size <- file.size(file)
  
  result <- data.frame(
    file_name = file,
    file_size = file_size,
    stringsAsFactors = FALSE
  )
  return(result)
}
