# WARNING - Generated by {fusen} from dev/flat_search_folder_size.Rmd: do not edit by hand

#' search_folder_size Title
#' Elle prend en paramètre un nom de dossier et une taille, et donne le tableau avec la taille des objets après avoir filtrée les fichiers plus grands que la taille.
#' @param directory nom de dossier
#' @param size_threshold seuil de taille des objets
#' @importFrom purrr map
#' @importFrom dplyr bind_rows filter
#' @return un tableau avec deux colonnes
#' @export
#' 
#' @examples
#' library(dplyr)
#' library(purrr)
#' temp_dir <- tempdir()
#' file1 <- file.path(temp_dir, "file1.csv")
#' file2 <- file.path(temp_dir, "file2.csv")
#' write.csv(iris, file1, row.names = FALSE)
#' write.csv(mtcars, file2, row.names = FALSE)
#'
#' # Utiliser la fonction search_folder_size avec un seuil de 1000 octets
#' result <- search_folder_size(temp_dir, 1000)
#' print(result)
#'
#' # Supprimer les fichiers temporaires après utilisation
#' unlink(file1)
#' unlink(file2)
search_folder_size <- function(directory, size_threshold) {
  # Obtenir les tailles de tous les fichiers dans le dossier
  all_files <- get_all_file_size(directory)
  
  # Filtrer les fichiers dont la taille est supérieure au seuil spécifié
  filtered_files <- all_files |> 
    filter(file_size > size_threshold)
  
  return(filtered_files)
}

